name: RegionSaver
version: '1.2.1'
main: fr.niixoz.regionSaver.RegionSaver
api-version: '1.21.6'
authors: [ NiixoZ ]
description: Region Saver plugin for EnderCube

commands:
  regionsaver:
    description: Permet de faire une save des Regions.
    usage: /regionsaver <save>
    aliases: [ rgsaver ]